export const cities = [
    { id: 101, cityname: 'Inverness' },
    { id: 102, cityname: 'Dongelberg' },
    { id: 103, cityname: 'Napoli' },
    { id: 104, cityname: 'Osasco' },
    { id: 105, cityname: 'Böblingen' },
    { id: 106, cityname: 'Gladstone' },
    { id: 107, cityname: 'Bucheon' },
    { id: 108, cityname: 'Bertiolo' },
    { id: 109, cityname: 'Gary' },
    { id: 110, cityname: 'Leiden' },
    { id: 111, cityname: 'Outremont' },
    { id: 112, cityname: 'Huesca' },
    { id: 113, cityname: 'Verrayes' },
    { id: 114, cityname: 'Lugo' },
    { id: 115, cityname: 'Diyarbakır' },
    { id: 116, cityname: 'Mondolfo' },
    { id: 117, cityname: 'Southend' },
    { id: 118, cityname: 'Issime' },
    { id: 119, cityname: 'Futrono' },
    { id: 120, cityname: 'Wolfsburg' }
];